### PR TITLE
Add persistent environment support to lua neovim client

### PR DESCRIPTION
**Pull request by glyh**
As title. The current approach let user specify which is the desired behavior. By default it use debug tools to store locals across evaluation. This can be improved with other approaches. I think multiple approaches are preferred because each one has its own drawback.

This PR is a continuation of #292.

EDIT:

<del>I also add support for input prompt, but seems like there's some problems here.</del>
The problem in input prompt are being fixed by Olical in the develop branch.

### CODE REVIEW

**Comment by glyh** [comment]
I'm not sure how you achieved this via coroutine because I didn't make a demo code that works... But it would be great if we can add that too.

**Comment by glyh** [comment]
I just refactor the code a bit and add support to input prompt, but it seems problematic. And I guess this has something to do with repeat.vim because whenever I tried `io.read()` I got this:
```
':silent! call repeat#set(",e", 1)\n'
```

**Comment by glyh** [comment]
I guess this is an issue. Directly call `(extract.prompt "Input required: ")` gives me the same result.

**Comment by glyh** [comment]
@Olical I'm pushing it but did you see this PR?

**Comment by Olical** [comment]
So the input prompt issue is something I'll solve with some unrelated work soon. Don't worry about that, it's a weird issue caused by hacks I had to do before Neovim had the proper Lua APIs to create mappings into Lua functions. Once I update how I perform a few of the mappings that issue will go away.

I've made small tweak to the output to make it valid Lua in the log buffer, another step on from your "return" lines you were inserting. I see why you had to do it, I'm prefixing results with `res =` for the same result but no syntax errors.

Seems better than what I had before! A little worried that overriding the io module will break a bunch of filesystem integration but we'll see. Still seems like an improvement! Merging!

**Comment by Olical** [comment]
Merged to `develop`, will release soon.

**Comment by glyh** [comment]
Sorry for my bad indentations, do you have a lint tool or something to fix them automatically?

**Comment by glyh** [comment]
Yeah, it would be good if we can somehow redirect it. But we have to write some codes at neovim's side. I made a issue for it.

**Pull request closed without merging**
