### PR TITLE
Adds basic Rust stdio support with evcxr

### PR DESCRIPTION
**Pull request by rafaeldelboni**
Evcxr has some limitations, but I was testing it with conjure and it was a fun experience:
https://github.com/google/evcxr/blob/main/evcxr_repl/README.md

This is just an experiment feel free to close this PR if it doesn't make sense to the tool roadmap :)

### CODE REVIEW

**Comment by Olical** [comment]
Really cool! I'll have a look! Maybe I'll just merge for now so people can try it out although I need to do the extra documentation / wiki work really, so I'll maybe hold off until I can do that.

**Comment by Olical** [comment]
Oh you did the README change! So it'd just be the `.txt` help file and the wiki page.

**Comment by rafaeldelboni** [comment]
You mean this kind of file?
https://github.com/Olical/conjure/blob/master/doc/conjure-client-scheme-stdio.txt

I can do this :)

**Comment by Olical** [comment]
Nice this looks good! Merging! Hopefully we can get feedback or people trying it out. I'll leave it on develop for a bit before fully releasing. Thank you!

**Pull request merged**
